# Generated by Django 3.2.3 on 2024-04-13 17:21

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_auto_20240410_2215'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='not_self_follow'),
        ),
    ]
