# Generated by Django 3.2.3 on 2024-04-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0008_auto_20240414_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецепта'},
        ),
    ]
