name: Foodgram Main Workflow

on:
  push:
    branches:
      -master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install depencies
        run: |
         python -m pip install --upgrade pip
         pip install -r ./backend/requirements.txt
         
      - name: Test with Flake8 and Django tests
        run: |
         python -m flake8 backend/
         cd backend/
         python manage.py test
